In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet(r"C:\Users\ASUS\Downloads\fhvhv_tripdata_2026-01.parquet")

In [3]:
df.shape

(20940373, 25)

In [28]:
zones_df = pd.read_csv(r"C:\Users\ASUS\Downloads\taxi_zone_lookup.csv")

In [29]:
zones_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [5]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,cbd_congestion_fee
0,HV0003,B03404,B03404,2026-01-01 00:50:37,2026-01-01 00:52:31,2026-01-01 00:54:30,2026-01-01 01:13:23,262,79,4.300,...,2.75,0.0,0.00,21.10,N,N,N,N,N,1.5
1,HV0003,B03404,B03404,2026-01-01 00:09:12,2026-01-01 00:12:17,2026-01-01 00:12:39,2026-01-01 00:22:42,195,52,1.890,...,0.00,0.0,0.00,9.10,N,N,N,N,N,0.0
2,HV0003,B03404,B03404,2026-01-01 00:16:16,2026-01-01 00:29:33,2026-01-01 00:31:34,2026-01-01 00:55:21,25,181,1.840,...,0.00,0.0,2.67,21.94,N,N,N,N,N,0.0
3,HV0005,B03406,NaN,2026-01-01 00:08:19,2026-01-01 00:09:08,2026-01-01 00:09:37,2026-01-01 00:22:12,141,226,3.307,...,2.75,0.0,0.00,13.42,N,N,N,N,Y,1.5
4,HV0005,B03406,NaN,2026-01-01 00:21:16,2026-01-01 00:26:30,2026-01-01 00:26:40,2026-01-01 00:39:06,226,226,2.060,...,0.00,0.0,2.98,11.39,N,N,N,N,Y,0.0

In [6]:
df.columns

Index(['hvfhs_license_num', 'dispatching_base_num', 'originating_base_num',
       'request_datetime', 'on_scene_datetime', 'pickup_datetime',
       'dropoff_datetime', 'PULocationID', 'DOLocationID', 'trip_miles',
       'trip_time', 'base_passenger_fare', 'tolls', 'bcf', 'sales_tax',
       'congestion_surcharge', 'airport_fee', 'tips', 'driver_pay',
       'shared_request_flag', 'shared_match_flag', 'access_a_ride_flag',
       'wav_request_flag', 'wav_match_flag', 'cbd_congestion_fee'],
      dtype='str')

In [9]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.isnull().sum()

hvfhs_license_num             0
dispatching_base_num          0
originating_base_num    5676843
request_datetime              0
on_scene_datetime             0
pickup_datetime               0
dropoff_datetime              0
PULocationID                  0
DOLocationID                  0
trip_miles                    0
trip_time                     0
base_passenger_fare           0
tolls                         0
bcf                           0
sales_tax                     0
congestion_surcharge          0
airport_fee                   0
tips                          0
driver_pay                    0
shared_request_flag           0
shared_match_flag             0
access_a_ride_flag            0
wav_request_flag              0
wav_match_flag                0
cbd_congestion_fee            0
dtype: int64

In [10]:
columns_to_keep = [
        'hvfhs_license_num', 'request_datetime', 'pickup_datetime', 'dropoff_datetime',
        'PULocationID', 'DOLocationID', 'trip_miles', 'trip_time',
        'base_passenger_fare', 'tips', 'driver_pay', 'cbd_congestion_fee']
df = df[columns_to_keep]

In [11]:
df.head()

,hvfhs_license_num,request_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tips,driver_pay,cbd_congestion_fee
0,HV0003,2026-01-01 00:50:37,2026-01-01 00:54:30,2026-01-01 01:13:23,262,79,4.300,1133,31.24,0.00,21.10,1.5
1,HV0003,2026-01-01 00:09:12,2026-01-01 00:12:39,2026-01-01 00:22:42,195,52,1.890,604,8.95,0.00,9.10,0.0
2,HV0003,2026-01-01 00:16:16,2026-01-01 00:31:34,2026-01-01 00:55:21,25,181,1.840,1427,24.06,2.67,21.94,0.0
3,HV0005,2026-01-01 00:08:19,2026-01-01 00:09:37,2026-01-01 00:22:12,141,226,3.307,755,24.91,0.00,13.42,1.5
4,HV0005,2026-01-01 00:21:16,2026-01-01 00:26:40,2026-01-01 00:39:06,226,226,2.060,746,17.86,2.98,11.39,0.0

In [12]:
df.isnull().sum()

hvfhs_license_num      0
request_datetime       0
pickup_datetime        0
dropoff_datetime       0
PULocationID           0
DOLocationID           0
trip_miles             0
trip_time              0
base_passenger_fare    0
tips                   0
driver_pay             0
cbd_congestion_fee     0
dtype: int64

In [13]:
df = df[
        (df['trip_miles'] > 0) & 
        (df['base_passenger_fare'] > 0) & 
        (df['driver_pay'] > 0) &
        (df['pickup_datetime'] >= df['request_datetime'])]

In [14]:
df.shape

(20569277, 12)

In [15]:
df['wait_time_minutes'] = (df['pickup_datetime'] - df['request_datetime']).dt.total_seconds() / 60

In [20]:
df.drop(columns=['request_datetime', 'dropoff_datetime'], inplace=True)

In [16]:
df['company_margin'] = df['base_passenger_fare'] - df['driver_pay']

In [17]:
df['pickup_hour'] = df['pickup_datetime'].dt.hour
df['pickup_day_of_week'] = df['pickup_datetime'].dt.day_name()

In [21]:
df.head()

,hvfhs_license_num,pickup_datetime,PULocationID,DOLocationID,trip_miles,trip_time,base_passenger_fare,tips,driver_pay,cbd_congestion_fee,wait_time_minutes,company_margin,pickup_hour,pickup_day_of_week
0,HV0003,2026-01-01 00:54:30,262,79,4.300,1133,31.24,0.00,21.10,1.5,3.883333,10.14,0,Thursday
1,HV0003,2026-01-01 00:12:39,195,52,1.890,604,8.95,0.00,9.10,0.0,3.450000,-0.15,0,Thursday
2,HV0003,2026-01-01 00:31:34,25,181,1.840,1427,24.06,2.67,21.94,0.0,15.300000,2.12,0,Thursday
3,HV0005,2026-01-01 00:09:37,141,226,3.307,755,24.91,0.00,13.42,1.5,1.300000,11.49,0,Thursday
4,HV0005,2026-01-01 00:26:40,226,226,2.060,746,17.86,2.98,11.39,0.0,5.400000,6.47,0,Thursday

In [22]:
df['hvfhs_license_num'] = df['hvfhs_license_num'].astype('category')
df['pickup_day_of_week'] = df['pickup_day_of_week'].astype('category')

In [23]:
df['PULocationID'] = df['PULocationID'].astype('uint16')
df['DOLocationID'] = df['DOLocationID'].astype('uint16')
df['pickup_hour'] = df['pickup_hour'].astype('int8')
df['trip_time'] = df['trip_time'].astype('int32')

In [24]:
float_cols = ['trip_miles', 'base_passenger_fare', 'tips', 'driver_pay', 
              'cbd_congestion_fee', 'wait_time_minutes', 'company_margin']
for col in float_cols:
    df[col] = df[col].astype('float32')

In [27]:
df.to_parquet("fact_trips_2026_01", index=False, engine='pyarrow', compression='snappy')

In [30]:
zones_df.to_csv("dim_zones", index=False)